version: '3'
services:
  #
  # ecas-frontend
  #
  ecas-frontend:
    build:
      context: ..
      dockerfile: docker/ecas-frontend/Dockerfile
    working_dir: /web-app
    ports:
      - 8080:80
    networks:
      - webnet
    environment:
      - APP_KEY=base64:sf+TeOK14bHa/pqupMwHbV5MUBFeZF/OPFh+LU++0w8=
      - APP_DEBUG=true
      - APP_URL=http://localhost


  #
  # ecas-frontend-dev
  #
  ecas-frontend-dev:
    build:
      context: ..
      dockerfile: docker/ecas-frontend/Dockerfile-dev
    working_dir: /web-app
    ports:
      - 8081:80
    volumes:
      - ../web-app:/web-app
    networks:
      - webnet
    environment:
      - CHOKIDAR_USEPOLLING=true
      - APP_KEY=base64:sf+TeOK14bHa/pqupMwHbV5MUBFeZF/OPFh+LU++0w8=
      - APP_DEBUG=true
networks:
  webnet: